name: CI and CD
on:
  push:
    branches:
      - deployment
  workflow_dispatch:
concurrency:
  group: deploy
  cancel-in-progress: true
jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yaml
  deploy:
    name: Deploy artifacts to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    needs:
      - ci
    steps:
      - uses: actions/checkout@v3
        with:
          ref: deployment
          fetch-depth: '0'
      - name: Rebase
        run: git rebase origin/main
      - name: Setup Node.js with Volta
        uses: ./.github/actions/setup-node
      - name: Install git-conventional-commits
        run: npm install -g git-conventional-commits
      - name: Output new version
        id: ver
        run: |
          NEW_VER=$(git-conventional-commits version)
          echo "New ver: v$NEW_VER"
          echo "NEW_VER_NUM=$NEW_VER" >> $GITHUB_OUTPUT
          echo "NEW_VER=v$NEW_VER" >> $GITHUB_OUTPUT
      - name: Git as GitHub Actions Bot
        uses: Lucky3028/git-as-gha@v1.0.1
      - name: Bump and push changes
        run: |
          yarn config set version-git-message "chore: bump ver to v%s"
          yarn version --new-version $NEW_VER_NUM
          git push origin deployment
          git push origin "$NEW_VER"
        env:
          NEW_VER_NUM: ${{ steps.ver.outputs.NEW_VER_NUM }}
          NEW_VER: ${{ steps.ver.outputs.NEW_VER }}
      - name: Build
        run: yarn build
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Output CHANGELOG
        run: git-conventional-commits changelog --release $NEW_VER --file 'CHANGELOG.md'
        env:
          NEW_VER: ${{ steps.ver.outputs.NEW_VER }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          tag_name: v${{ steps.ver.outputs.NEW_VER }}
      - name: Create and merge PR to push bump
        run: |
          gh pr create --base main --head deployment -t "Deploy($NEW_VER)" -b ""
          gh pr merge --auto -m
        env:
          NEW_VER: ${{ steps.ver.outputs.NEW_VER }}
