name: CI
on:
  workflow_call:
  push:
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js with Volta
        uses: ./.github/actions/setup-node
      - name: Run ESLint
        run: yarn es
  format:
    name: Run Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js with Volta
        uses: ./.github/actions/setup-node
      - name: Run Prettier
        run: yarn format
  test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Setup Node.js with Volta
        uses: ./.github/actions/setup-node
      - name: Run coverage tests
        run: yarn test:coverage
      - name: Edit result file
        run: tail -n +2 coverage/result-jest.txt | head -n -1 > result.txt
      - name: Write coverages to summary
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require("fs").promises;
            const jest = await fs.readFile("./result.txt").then((b) => b.toString());
            const output = `\n${jest}`;
            await core.summary
              .addHeading('Jest Coverages')
              .addRaw(output)
              .write();
